#!/usr/bin/env bash
# Configration
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y
echo -e "\nSetting up some minor stuff.\n"
# service start
sudo service nginx start
# allow firewall
sudo ufw allow 'Nginx HTTP'
# Ownership
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
# backup
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
# index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
# start again nginx
sudo service nginx restart
echo -e "\nCompleted. ✅\n"
