#!/usr/bin/env bash
# Configuration
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y
echo -e "\nSetting up some minor stuff.\n"
# service start
sudo service nginx start
# firewall
sudo ufw allow 'Nginx HTTP'
# ownership
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
# backup
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
# index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
# setup
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# start again nginx
sudo service nginx restart
echo -e "\nCompleted.\n"
