#!/usr/bin/env bash
# Configration
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y
echo -e "\nSetting up some minor stuff.\n"
# start service
sudo service nginx start
# firwall
sudo ufw allow 'Nginx HTTP'
# Ownership
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
# index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
# set
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
# nginx start again
sudo service nginx restart
echo -e "\nCompleted.\n"
