#!/usr/bin/env bash
#displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number

for j in {1..100}
do
  if (( j % 3 == 0 && j % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( j % 3 == 0 ))
  then
    echo "Fizz"
  elif (( j % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$j"
  fi
done
