#!/usr/bin/env bash
#  Client configuration file
Host *
     passwordAuthentication no
     IdentityFile ~/.ssh/school
     SendEnv LANG LC_*
     HashKnownHosts yes
     GSSAPIAuthentication yes
     GSSAPIDelegateCredentials no
